version: '3'

services:
  web:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8083:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge