name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Set tag for Docker image
      id: set_tag
      run: |
        TAG=${GITHUB_SHA::8}-$(date +%s)
        IMAGE="ghcr.io/paytjs/crm-web"
        echo ::set-output name=tagged_image::${IMAGE}:${TAG}
        echo ::set-output name=tag::${TAG}

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.build-cache
        key: ${{ runner.os }}-multi-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-multi-build

    - name: Build image
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        tags: ${{ steps.set_tag.outputs.tagged_image }}
        push: true
        cache-from: type=gha
        cache-to: type=gha

    - name: Run ansible playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yaml
        directory: ./ansible/
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        options: |
          --inventory host
          --extra-vars image_tag=${{ steps.set_tag.outputs.tag }}
          --extra-vars docker_username=${{ github.actor }} 
          --extra-vars docker_pass=${{ secrets.GITHUB_TOKEN }}